### ISSUE TITLE
bug: verification email contains no link

### ISSUE THREAD

**Issue by nguyenvukhang** [project-orbital/frontend#102]
![Screen Shot 2022-07-27 at 21 27 09](https://user-images.githubusercontent.com/10664455/181258569-56cb457f-327b-4701-8354-b078268e706f.png)

Expected: there to be a link to verify email
Actual: can't find the link (I also tried clicking every word, just in case the link was behind anything)

**Comment by nguyenvukhang** [comment]
upon closer inspection, there is a buried href:
![Screen Shot 2022-07-27 at 21 31 26](https://user-images.githubusercontent.com/10664455/181259551-53dc261b-f913-4097-81d1-baf8f0ec137d.png)

Seems like there's an extra `3D` blocking the XML from being valid.
Navigating to the link provided does successfully verify the email

**Comment by jontmy** [comment]
Thanks for catching this! We manually tested the email verification using Outlook which renders the link correctly, and therefore never realized that the link was in fact broken.

<img width="1411" alt="Screenshot 2022-07-27 at 23 30 58" src="https://user-images.githubusercontent.com/50949210/181288662-07c35e37-5de7-4bc6-9b31-b9a4b9ba3f26.png">

We're working on a fix now.

**Comment by jontmy** [comment]
Wow, fixed by reverting the email message to an older working version. I'm completely stumped by this bug, cuz it wasn't a typo in the HTML as far as I can see.

Diff:
https://github.com/project-orbital/backend/pull/56/commits/333b12b6f62773c9852b4427f90369651f51d9d9
